name = "Andrew's Vanilla Modpack"
author = "andrwcrr"
version = "fabric-1.20.1-4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "632159febb6e529b9c4f7f6358439ad4975bd31643e8ecafde5bfc313c3689d2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
